data:
  "":
    description: |
      The corpus contains 1,832,307 xml files, each with combined book
      metadata from Amazon and LibraryThing. The filenames correspond to the
      ID number of each book on LibraryThing. Note that some works can have
      multiple editions, therefore a single book description can have multiple
      book titles, creators, etc.

      Each description has the following complex elements:
      - editions (edition information: ISBN, title, creators, publisher, etc)
      - similarproducts (ISBNs of books bought by the same customers)
      - browseNodes (Amazon categories)
      - subjects (library subject headings)
      - reviews (Amazon user reviews with ratings)
      - tags (LibraryThing user tags)

      The whole corpus is available as a single gzipped tarball file. The file
      unpacks into a single directory, with subdirectories corresponding to
      the last three digits of the IDs. Thus, all IDs ending in 352 are
      stored in the 352/ subdirectory.

      This corpus is derived from the INEX Amazon/LibraryThing corpus made
      for the INEX Interactive Track and Social Book Search Track.
    tags: [collaborative filtering, recommendation]
    statistics:
      files: 1_832_307

    datapath: .
    files:
      bookrec-data.train:
        description: Train data
        format: 
          columns: [user, item, date, score, tags]

      bookrec-data.final-train:
        description: Train data
        format:
          columns: [user, item, date, score, tags]

