name: SQuAD
title: The Stanford Question Answering Dataset
tags:
  - language comprehension
  - natural language inference
  - question anwering
licence: CC BY-SA 3.0
links:
  website: https://rajpurkar.github.io/SQuAD-explorer/

description: |
  Stanford Question Answering Dataset (SQuAD) is a reading comprehension
  dataset, consisting of questions posed by crowdworkers on a set of
  Wikipedia articles, where the answer to every question is a segment of
  text, or span, from the corresponding reading passage, or the question
  might be unanswerable.

data:
  v2:
    links:
      paper: http://arxiv.org/abs/1806.03822
    download:
      handler: /multiple/Simple
      list:
        train:  
          handler: /single/File
          url: https://rajpurkar.github.io/SQuAD-explorer/dataset/train-v2.0.json
        dev: 
          handler: /single/File
          url: https://rajpurkar.github.io/SQuAD-explorer/dataset/dev-v2.0.json
